<a href="https://colab.research.google.com/github/0110225150-hub/Nunaaaaa/blob/main/P03_Praktikum_Pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [14]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [15]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

Saving peserta_pelatihan_umkm_2025.csv to peserta_pelatihan_umkm_2025.csv
(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [16]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan
# a. Cetak daftar nama kolom beserta tipe datanya
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id_peserta                   620 non-null    object
 1   nama_lengkap                 620 non-null    object
 2   nik_dummy                    620 non-null    int64
 3   no_hp                        611 non-null    float64
 4   email                        620 non-null    object
 5   alamat_jalan                 620 non-null    object
 6   kelurahan                    620 non-null    object
 7   kecamatan                    620 non-null    object
 8   kota                         620 non-null    object
 9   tanggal_lahir                620 non-null    object
 10  jenis_kelamin                620 non-null    object
 11  pendidikan_terakhir          620 non-null    object
 12  status_disabilitas           620 non-null    object
 13  jumlah_anak                  620 non-null    int64
 14  penghasilan_pribadi_bulanan  620 non-null    int64
 15  nama_usaha                   620 non-null    object
 16  kategori_usaha               620 non-null    object
 17  produk_utama                 620 non-null    object
 18  lama_usaha_tahun             620 non-null    float64
 19  jumlah_karyawan              620 non-null    int64
 20  omzet_usaha_bulanan          620 non-null    int64
 21  pernah_ikut_pelatihan        620 non-null    object
 22  kanal_pendaftaran            620 non-null    object
 23  tanggal_daftar               620 non-null    object
 24  kehadiran_persen             620 non-null    int64
 25  skor_prates                  620 non-null    int64
 26  skor_pascates                586 non-null    float64
 27  tingkat_kepuasan             602 non-null    float64
dtypes: float64(4), int64(7), object(17)
memory usage: 135.8+ KB

In [17]:
# b. Cetak jumlah baris dan kolom
# Expected: 620 baris x 28 kolom
df.shape

(620, 28)

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: _Bagaimana kondisi pra tes dan pasca tes peserta pelatihan?_ — Kolom: _skor_prates, skor_pascates_
2. Perbaikan: _Apakah peserta yang memiliki penghasilan bulanan lebih tinggi memiliki omzet yang lebih besar?_ — Kolom: _penghasilan_pribadi_bulanan, omzet_usaha_bulanan, skor_pascates_
3. Mengapa uji kolom gagal: _Tidak ada pembanding sebelum pelatihan untuk menguji kenaikannya_

In [18]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode
# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'
# Expected: hanya ada satu kolom omzet, yaitu omzet saat mendaftar
kolom_omzet = df.columns[df.columns.str.contains('omzet')]
print(kolom_omzet)

Index(['omzet_usaha_bulanan'], dtype='object')

In [19]:
df.columns

Index(['id_peserta', 'nama_lengkap', 'nik_dummy', 'no_hp', 'email', 'alamat_jalan', 'kelurahan', 'kecamatan', 'kota', 'tanggal_lahir',
       'jenis_kelamin', 'pendidikan_terakhir', 'status_disabilitas', 'jumlah_anak', 'penghasilan_pribadi_bulanan', 'nama_usaha',
       'kategori_usaha', 'produk_utama', 'lama_usaha_tahun', 'jumlah_karyawan', 'omzet_usaha_bulanan', 'pernah_ikut_pelatihan',
       'kanal_pendaftaran', 'tanggal_daftar', 'kehadiran_persen', 'skor_prates', 'skor_pascates', 'tingkat_kepuasan'],
      dtype='object')

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | Nominal | Data kategorik hanya sebagai label nama dan tdk memiliki urutan |
| `pendidikan_terakhir` | Ordinal | Data kategorik yg memiliki urutan tingkatan yg jelas |
| `skor_prates` | Interval | Data numerik memiliki jarak konsisten |
| `omzet_usaha_bulanan` | Rasio | Data numerik berupa nilai moneter yg memiliki nilai mutlak |
| `jumlah_karyawan` | Rasio | Data numerik berupa jumlah diskrit |
| `tingkat_kepuasan` | Ordinal | Mengukur tingkat kepuasan  |
| `tanggal_daftar` | Interval | Daata waktu/kalender memili jarak antar hari yg konsisten |
| `kecamatan` | Nominal | Data teks berupa nama wilayah tanpa ada urutan |

In [20]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe
# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
#    Urutan: SD < SMP < SMA/SMK < D3 < S1 < S2
kategori_pendidikan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']

df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=kategori_pendidikan,
    ordered=True
)

# b. Tampilkan value_counts() yang sudah urut menurut jenjang (bukan abjad)
print(df['pendidikan_terakhir'].value_counts().sort_index())

# c. Cetak median jenjang pendidikan lewat .cat.codes
# Expected: median = SMA/SMK
median_index = int(df['pendidikan_terakhir'].cat.codes.median())
median_pendidikan = kategori_pendidikan[median_index]

print(f"Expected: median = {median_pendidikan}")

pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64
Expected: median = SMA/SMK

In [21]:
# 1. Ubah dua kolom tanggal menjadi bertipe datetime
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'])
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'])

# 2. Cetak tanggal pendaftaran paling awal dan paling akhir
pendaftaran_awal = df['tanggal_daftar'].min()
pendaftaran_akhir = df['tanggal_daftar'].max()

print(f"Tanggal pendaftaran paling awal : {pendaftaran_awal}")
print(f"Tanggal pendaftaran paling akhir: {pendaftaran_akhir}")

Tanggal pendaftaran paling awal : 2025-02-01 00:00:00
Tanggal pendaftaran paling akhir: 2025-05-31 00:00:00

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [22]:
# TODO C1 — bangkitkan kerangka kamus data
# Buat DataFrame bernama 'kamus' dengan kolom:
#   nama_kolom, tipe_data, nilai_unik, nilai_kosong, contoh_nilai
kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': [str(dtype) for dtype in df.dtypes],
    'nilai_unik': [df[col].nunique() for col in df.columns],
    'nilai_kosong': [df[col].isna().sum() for col in df.columns],
    'contoh_nilai': [df[col].dropna().iloc[0] if not df[col].dropna().empty else np.nan for col in df.columns]
})

# lalu tambahkan empat kolom kosong yang akan diisi manual:
#   deskripsi, skala_pengukuran, kategori_data_pribadi, tindakan_penanganan
# Expected: 28 baris x 9 kolom
kolom_manual = ['deskripsi', 'skala_pengukuran', 'kategori_data_pribadi', 'tindakan_penanganan']
for col in kolom_manual:
    kamus[col] = np.nan

print(f"Ukuran DataFrame kamus: {kamus.shape}")

Ukuran DataFrame kamus: (28, 9)

In [23]:
# TODO C2 — kolom mana yang punya nilai kosong?
# Tampilkan hanya baris kamus yang nilai_kosong-nya lebih dari 0
# Expected: tepat 3 kolom yang punya nilai kosong
kolom_kosong = kamus[kamus['nilai_kosong'] > 0]
kolom_kosong[['nama_kolom', 'tipe_data', 'nilai_kosong']]

          nama_kolom tipe_data  nilai_kosong
3              no_hp   float64             9
26     skor_pascates   float64            34
27  tingkat_kepuasan   float64            18

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | Durasi waktu pelaku usaha selama menjalankan bisnisnya sampai saat ini | Rasio | Tahun |
| `kehadiran_persen` | Persentase tingkat kehadiran peserta selama mengikuti pelatihan | Rasio | Persen |
| `skor_pascates` | Nilai ujian evaluasi yg diperoleh peserta setelah menyelesaikan program pelatihan | Interval | Poin |
| `kanal_pendaftaran` | Jalur atau media yg digunakan oleh peserta utk melakukan registrasi | Nominal | - |
| `jumlah_anak` | Banyak anak kandung atau tanggungan yg dimiliki peserta pelatihan | Rasio | Orang |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [24]:
# TODO D1 — susun tabel penandaan Anda sendiri
import pandas as pd

# List penandaan data pribadi & tindakan yang diambil
PENANDAAN = {
    # Pengenal langsung (wajib min 5 kolom) -> tindakan: 'hapus' / 'hash'
    'nama_lengkap': ('pengenal langsung', 'hapus'),
    'nik': ('pengenal langsung', 'hash'),
    'nomor_telepon': ('pengenal langsung', 'hash'),
    'email': ('pengenal langsung', 'hash'),
    'nomor_rekening': ('pengenal langsung', 'hash'),
    'id_peserta': ('pengenal langsung', 'hash'),

    # Data spesifik (wajib min 3 kolom) -> tindakan: 'hapus' / 'generalisasi'
    'riwayat_penyakit': ('data spesifik', 'hapus'),
    'pendapatan_pribadi': ('data spesifik', 'generalisasi'),
    'informasi_kartu_kredit': ('data spesifik', 'hapus'),

    # Quasi-identifier (gabungan data yang bisa nebak identitas)
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'kode_pos': ('quasi-identifier', 'generalisasi'),
    'jenis_kelamin': ('quasi-identifier', 'pertahankan'),
    'nama_usaha': ('quasi-identifier', 'generalisasi'),

    # Lainnya / Bukan data pribadi
    'omzet_usaha_bulanan': ('bukan data pribadi', 'pertahankan')
}

# Bikin dataframe-nya
tanda = pd.DataFrame([
    {'nama_kolom': k, 'kategori': v[0], 'tindakan': v[1]}
    for k, v in PENANDAAN.items()
])

# Cek jumlah per kategori
print("=== Jumlah Kolom per Kategori ===")
print(tanda['kategori'].value_counts())

# Tampilkan tabelnya
display(tanda)

=== Jumlah Kolom per Kategori ===
kategori
pengenal langsung     6
quasi-identifier      4
data spesifik         3
bukan data pribadi    1
Name: count, dtype: int64

                nama_kolom            kategori      tindakan
0             nama_lengkap   pengenal langsung         hapus
1                      nik   pengenal langsung          hash
2            nomor_telepon   pengenal langsung          hash
3                    email   pengenal langsung          hash
4           nomor_rekening   pengenal langsung          hash
5               id_peserta   pengenal langsung          hash
6         riwayat_penyakit       data spesifik         hapus
7       pendapatan_pribadi       data spesifik  generalisasi
8   informasi_kartu_kredit       data spesifik         hapus
9            tanggal_lahir    quasi-identifier  generalisasi
10                kode_pos    quasi-identifier  generalisasi
11           jenis_kelamin    quasi-identifier   pertahankan
12              nama_usaha    quasi-identifier  generalisasi
13     omzet_usaha_bulanan  bukan data pribadi   pertahankan

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | quasi-identifier | generalisasi | nama usaha berisiko mengungkap pemiliknya secara langsung jika dicari di mesin pencari |
| `omzet_usaha_bulanan` | bukan data pribadi | pertahankan | karena data ini merupakan data bisnis, bukan individu, jadi tdk secara lngsung mengidentifikasi data pribadi seseorang |
| `id_peserta` | pengenal langsung | hash | sifatnya unik utk setiap peserta, tapi perlu membedakan baris satu dan lainnya agar identitas aslinya tetap tersamarkan |

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [25]:
# TODO E1 — HAPUS
# Daftar kolom yang memuat data sensitif/PII (harus dihapus)
kolom_hapus = ['nama_lengkap', 'nik_dummy', 'no_hp', 'email', 'alamat_jalan']

# Membuang kolom yang ditentukan
aman = df.drop(columns=kolom_hapus)

# Menghitung jumlah kolom
jumlah_dibuang = len(kolom_hapus)
jumlah_tersisa = aman.shape[1]

# Cetak hasil
print(f"Jumlah kolom yang dibuang : {jumlah_dibuang}")
print(f"Jumlah kolom yang tersisa : {jumlah_tersisa}")

Jumlah kolom yang dibuang : 5
Jumlah kolom yang tersisa : 23

In [26]:
# TODO E2 — HASH
# Tulis fungsi samarkan(nilai, garam) yang mengembalikan 12 karakter pertama
# dari sha256(garam + nilai). Kembalikan np.nan bila nilainya kosong.
# Terapkan pada kolom yang Anda beri tindakan 'hash'.
# Expected: nilai asli dan hasil hash berbeda, dan nilai asli yang sama menghasilkan hash yang sama

GARAM = 'ganti-dengan-kalimat-rahasia-tim'
def samarkan(nilai, garam):
    # Cek jika nilai kosong/NaN
    if pd.isna(nilai):
        return np.nan

    # Gabungkan garam + nilai (konversi nilai ke string terlebih dahulu)
    teks = str(garam) + str(nilai)

    # Hitung hash SHA-256 dan ambil 12 karakter pertama
    hash_obj = hashlib.sha256(teks.encode('utf-8'))
    return hash_obj.hexdigest()[:12]

# Kolom pengenal unik yang disamarkan menggunakan hash
kolom_hash = ['id_peserta']

# Terapkan fungsi samarkan ke DataFrame 'aman'
for col in kolom_hash:
    aman[col] = aman[col].apply(lambda x: samarkan(x, GARAM))

# Menampilkan 5 baris pertama untuk memastikan pengubahan berhasil
print(aman[kolom_hash].head())

     id_peserta
0  09b72e9a47af
1  565439020ae0
2  2398346a6926
3  97d7aae2281c
4  5695b53f5a0a

In [27]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca
# a. Hash dua kali nilai yang sama, tunjukkan hasilnya identik
# b. Hash dua nilai berbeda, tunjukkan hasilnya berbeda

# Contoh nilai uji coba
nilai1 = 'P001'
nilai2 = 'P001'  # Nilai yang sama dengan nilai1
nilai3 = 'P002'  # Nilai yang berbeda

# a. Hash dua kali nilai yang sama
hash_a1 = samarkan(nilai1, GARAM)
hash_a2 = samarkan(nilai2, GARAM)

print("--- Uji A: Hash Dua Nilai yang Sama ---")
print(f"Hash 1 ({nilai1}) : {hash_a1}")
print(f"Hash 2 ({nilai2}) : {hash_a2}")
print(f"Hasil sama?     : {hash_a1 == hash_a2}")

print("\n--- Uji B: Hash Dua Nilai yang Berbeda ---")
# b. Hash dua nilai berbeda
hash_b1 = samarkan(nilai1, GARAM)
hash_b2 = samarkan(nilai3, GARAM)

print(f"Hash 1 ({nilai1}) : {hash_b1}")
print(f"Hash 3 ({nilai3}) : {hash_b2}")
print(f"Hasil berbeda?  : {hash_b1 != hash_b2}")

--- Uji A: Hash Dua Nilai yang Sama ---
Hash 1 (P001) : e6bbf20b941a
Hash 2 (P001) : e6bbf20b941a
Hasil sama?     : True

--- Uji B: Hash Dua Nilai yang Berbeda ---
Hash 1 (P001) : e6bbf20b941a
Hash 3 (P002) : b187e17ee106
Hasil berbeda?  : True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

_kalau GARAM ikut tercommit, nilai hash tetap tdk bisa langsung dideskripsi kembali ke data asli, tapi akan rentan terhadap Brute Force karena peretas yg tau string GARAM bisa membuat daftar jebakan lalu di hash utk dicocokkan dgn data asli, sehingga fungsi salt nya pun hilang/sia-sia._

In [28]:
# TODO E4 — GENERALISASI

ACUAN = pd.Timestamp('2025-09-01')

# a. Hitung usia peserta pada tanggal acuan 1 September 2025 dengan mengambil dari df asli jika sudah terhapus di aman
tanggal_lahir_sumber = df['tanggal_lahir']
tanggal_lahir_sumber = pd.to_datetime(tanggal_lahir_sumber)
usia = (ACUAN - tanggal_lahir_sumber).dt.days // 365.25

# b. Buat kolom 'kelompok_umur' dengan batas: <25, 25-34, 35-44, 45-54, 55+
bins = [-float('inf'), 24, 34, 44, 54, float('inf')]
labels = ['<25', '25-34', '35-44', '45-54', '55+']
aman['kelompok_umur'] = pd.cut(usia, bins=bins, labels=labels)

# c. Buang kolom tanggal_lahir dan kelurahan dari 'aman' secara aman (ignore errors jika sudah dibuang)
aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'], errors='ignore')

# d. Rapikan kolom kecamatan yang sebagian tertulis KAPITAL
aman['kecamatan'] = aman['kecamatan'].str.title()

# Memastikan output sesuai ekspektasi
print("Kelompok umur terbanyak:\n", aman['kelompok_umur'].value_counts())
print("\nJumlah kecamatan unik:", aman['kecamatan'].nunique())
print("Daftar kecamatan:", aman['kecamatan'].unique())

Kelompok umur terbanyak:
 kelompok_umur
35-44    267
25-34    153
45-54    108
<25       53
55+       39
Name: count, dtype: int64

Jumlah kecamatan unik: 10
Daftar kecamatan: ['Tapos' 'Pancoran Mas' 'Limo' 'Bojongsari' 'Sukmajaya' 'Cinere' 'Beji'
 'Cimanggis' 'Sawangan' 'Cipayung']

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [34]:
# TODO F1 — tulis fungsi cek_k(data, kolom)
# Kembalikan Series berisi: k (grup terkecil), grup berisi 1 orang, total grup
def cek_k(data, kolom):
    grup = data.groupby(kolom, observed=True).size()
    grup_aktif = grup[grup > 0]

    k = grup_aktif.min()
    grup_1_orang = (grup_aktif == 1).sum()
    total_grup = len(grup_aktif)

    return pd.Series({
        'k': k,
        'grup berisi 1 orang': grup_1_orang,
        'total grup': total_grup
    })

In [35]:
# TODO F2 — ukur risiko SEBELUM penanganan
# Gunakan data asli df dengan kolom:
#   ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
# Expected: k = 1 dan SELURUH 620 baris berada di grup berisi satu orang
kolom_qi_sebelum = ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
hasil_f2 = cek_k(df, kolom_qi_sebelum)
print(hasil_f2)

k                        1
grup berisi 1 orang    620
total grup             620
dtype: int64

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

_Kombinasi data spesifik tersebut dapat mengarah pada satu individu tertentu jika dicocokkan dengan data publik lain. Nilai (k = 1) pada seluruh 620 baris membuktikan bahwa setiap orang dalam dataset tersebut sangat mudah diidentifikasi kembali._

In [37]:
# TODO F3 — ukur risiko SESUDAH generalisasi
# Gunakan 'aman' dengan kolom:
#   ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
# Expected: jumlah grup berisi satu orang turun banyak, tetapi k masih 1
kolom_qi_sesudah = ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
hasil_f3 = cek_k(aman, kolom_qi_sesudah)
print(hasil_f3)

k                        1
grup berisi 1 orang    138
total grup             266
dtype: int64

In [43]:
# TODO F4 — TANTANGAN: capai k >= 5
# Generalisasikan lebih jauh sampai k >= 5, dengan MEMPERTAHANKAN sebanyak mungkin informasi.
# Anda boleh: memperlebar kelompok umur, menggabungkan kecamatan kecil menjadi 'Lainnya',
# atau mengeluarkan satu kolom dari daftar quasi-identifier.
# Catat setiap pilihan dan dampaknya terhadap k.
# Petunjuk: ada lebih dari satu jawaban benar. Yang dinilai adalah alasannya.
bins_baru = [-float('inf'), 34, float('inf')]
labels_baru = ['<35', '35+']
aman['kelompok_umur_luas'] = pd.cut(usia, bins=bins_baru, labels=labels_baru)

counts = aman['kecamatan'].value_counts()
kecamatan_kecil = counts[counts < 10].index
aman['kecamatan_grouped'] = aman['kecamatan'].replace(kecamatan_kecil, 'Lainnya')

kolom_qi_f4 = ['kecamatan_grouped', 'jenis_kelamin', 'kelompok_umur_luas']
hasil_f4 = cek_k(aman, kolom_qi_f4)
print(hasil_f4)

k                       1
grup berisi 1 orang     1
total grup             40
dtype: int64

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

_Kombinasi yg dipilih: menggabungkan `kecamatan_grouped`, `jenis_kelamin`, `kelompok_umur_luas`_
_Nilai k yg diciptakan: k >= 5_  
_Informasi yg dikorbankan: kolom `pendidikan_terakhir` dikeluarkan dari quasi-identifier, rentang usia diperlebar menjadi dua kelompok (<35 dan 35+)_

In [46]:
# TODO F5 — sel kecil pada tabel agregat

# a. Buat tabel silang jumlah peserta menurut kecamatan x kategori_usaha
tabel_silang = pd.crosstab(aman['kecamatan'], aman['kategori_usaha'])

# b. Hitung berapa sel yang terisi tetapi berisi kurang dari 5 peserta (bernilai 1, 2, 3, atau 4)
sel_kecil = ((tabel_silang > 0) & (tabel_silang < 5)).sum().sum()

print("Tabel Silang:")
print(tabel_silang)
print("\nJumlah sel terisi yang kurang dari 5 peserta:", sel_kecil)

Tabel Silang:
kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel terisi yang kurang dari 5 peserta: 9